In [1]:
import googlemaps
import pandas as pd

df = pd.read_csv('hoikuen.csv')

gm = googlemaps.Client(key='xxxxxxxxx')
for i, r in df.iterrows():
    res = gm.geocode(r['住所'])
    df.loc[i,'latitude'] = res[0]['geometry']['location']['lat']
    df.loc[i,'longitude'] = res[0]['geometry']['location']['lng']
    print(i)
    print(res[0]['geometry']['location'])

0
{'lat': 35.5994527, 'lng': 139.6801106}
1
{'lat': 35.60526979999999, 'lng': 139.6757044}
2
{'lat': 35.6154624, 'lng': 139.6425391}
3
{'lat': 35.6177344, 'lng': 139.6241309}
4
{'lat': 35.6348913, 'lng': 139.6303933}
5
{'lat': 35.6317882, 'lng': 139.6278758}
6
{'lat': 35.6256378, 'lng': 139.6366415}
7
{'lat': 35.6246496, 'lng': 139.6372591}
8
{'lat': 35.61057700000001, 'lng': 139.6525027}
9
{'lat': 35.626843, 'lng': 139.653539}
10
{'lat': 35.6160642, 'lng': 139.6578091}
11
{'lat': 35.617519, 'lng': 139.6608933}
12
{'lat': 35.6146671, 'lng': 139.6314666}
13
{'lat': 35.6091121, 'lng': 139.6531404}
14
{'lat': 35.6032541, 'lng': 139.6651987}
15
{'lat': 35.6046538, 'lng': 139.6419214}
16
{'lat': 35.6090118, 'lng': 139.6582425}
17
{'lat': 35.610345, 'lng': 139.6620494}
18
{'lat': 35.5968366, 'lng': 139.6550337}
19
{'lat': 35.6233428, 'lng': 139.6426985}
20
{'lat': 35.6267131, 'lng': 139.6525027}
21
{'lat': 35.624889, 'lng': 139.6305054}
22
{'lat': 35.6192608, 'lng': 139.6259635}
23
{'lat': 35.6182478, 'lng': 139.6323979}
24
{'lat': 35.6321207, 'lng': 139.6390324}
25
{'lat': 35.6337321, 'lng': 139.6429799}
26
{'lat': 35.6037901, 'lng': 139.6783162}
27
{'lat': 35.6077159, 'lng': 139.6480189}
28
{'lat': 35.6306072, 'lng': 139.627079}
29
{'lat': 35.6177668, 'lng': 139.6206053}
30
{'lat': 35.6102989, 'lng': 139.6392398}
31
{'lat': 35.6229978, 'lng': 139.660116}
32
{'lat': 35.6077939, 'lng': 139.6519182}
33
{'lat': 35.6198517, 'lng': 139.6657942}
34
{'lat': 35.6206368, 'lng': 139.6573655}
35
{'lat': 35.6328881, 'lng': 139.6430837}
36
{'lat': 35.6274763, 'lng': 139.6445516}
37
{'lat': 35.6213752, 'lng': 139.6438291}
38
{'lat': 35.63605769999999, 'lng': 139.6308241}
39
{'lat': 35.6300495, 'lng': 139.6372373}
40
{'lat': 35.6185848, 'lng': 139.6518855}
41
{'lat': 35.6116056, 'lng': 139.6527419}
42
{'lat': 35.6001958, 'lng': 139.6464586}
43
{'lat': 35.6002888, 'lng': 139.668129}
44
{'lat': 35.61023040000001, 'lng': 139.650749}
45
{'lat': 35.6329568, 'lng': 139.6442727}
46
{'lat': 35.5963832, 'lng': 139.6779542}
47
{'lat': 35.6057705, 'lng': 139.6574037}
48
{'lat': 35.634975, 'lng': 139.6255294}
49
{'lat': 35.6287097, 'lng': 139.6348913}
50
{'lat': 35.6080326, 'lng': 139.6479591}
51
{'lat': 35.6053748, 'lng': 139.643898}
52
{'lat': 35.616901, 'lng': 139.625431}
53
{'lat': 35.6244953, 'lng': 139.6589799}
54
{'lat': 35.6071271, 'lng': 139.6610927}
55
{'lat': 35.6286647, 'lng': 139.6372591}
56
{'lat': 35.5992323, 'lng': 139.6731327}
57
{'lat': 35.6129637, 'lng': 139.6364622}
58
{'lat': 35.6300402, 'lng': 139.6535988}
59
{'lat': 35.6063532, 'lng': 139.6551533}
60
{'lat': 35.6039785, 'lng': 139.6609332}
61
{'lat': 35.6311045, 'lng': 139.651855}
62
{'lat': 35.6248717, 'lng': 139.6606741}
63
{'lat': 35.6083136, 'lng': 139.6497725}
64
{'lat': 35.6465615, 'lng': 139.6532924}
65
{'lat': 35.6034642, 'lng': 139.6746478}
66
{'lat': 35.6034079, 'lng': 139.6477399}
67
{'lat': 35.6108193, 'lng': 139.6393312}
68
{'lat': 35.61193, 'lng': 139.6389726}
69
{'lat': 35.6246377, 'lng': 139.638076}
70
{'lat': 35.6272676, 'lng': 139.6345894}
71
{'lat': 35.60986949999999, 'lng': 139.6321589}
72
{'lat': 35.6170878, 'lng': 139.6261512}
73
{'lat': 35.6158776, 'lng': 139.6237394}
74
{'lat': 35.6149588, 'lng': 139.6218989}
75
{'lat': 35.62212110000001, 'lng': 139.6291507}
76
{'lat': 35.63195839999999, 'lng': 139.6451056}
77
{'lat': 35.6323315, 'lng': 139.6466838}
78
{'lat': 35.6465615, 'lng': 139.6532924}
79
{'lat': 35.65549439999999, 'lng': 139.6543163}
80
{'lat': 35.6037144, 'lng': 139.6529611}
81
{'lat': 35.6086772, 'lng': 139.630087}
82
{'lat': 35.6404502, 'lng': 139.6150982}
83
{'lat': 35.6474629, 'lng': 139.660126}
84
{'lat': 35.6491679, 'lng': 139.6309835}
85
{'lat': 35.63852000000001, 'lng': 139.6141677}
86
{'lat': 35.6433693, 'lng': 139.6111163}
87
{'lat': 35.6067329, 'lng': 139.6709358}
88
{'lat': 35.6294461, 'lng': 139.6517653}
89
{'lat': 35.67212689999999, 'lng': 139.6610927}
90
{'lat': 35.6339419, 'lng': 139.6608933}
91
{'lat': 35.6476712, 'lng': 139.6770502}
92
{'lat': 35.6316299, 'lng': 139.6433362}
93
{'lat': 35.6077502, 'lng': 139.6544358}
94
{'lat': 35.647499, 'lng': 139.6827367}
95
{'lat': 35.6318075, 'lng': 139.6561824}
96
{'lat': 35.616901, 'lng': 139.625431}
97
{'lat': 35.6258544, 'lng': 139.6349082}
98
{'lat': 35.6242665, 'lng': 139.6476564}
99
{'lat': 35.647792, 'lng': 139.680629}
100
{'lat': 35.632, 'lng': 139.6385542}
101
{'lat': 35.6106974, 'lng': 139.6306561}
102
{'lat': 35.6653539, 'lng': 139.6413237}
103
{'lat': 35.6508379, 'lng': 139.643635}
104
{'lat': 35.6508494, 'lng': 139.6376974}
105
{'lat': 35.646374, 'lng': 139.6705012}
106
{'lat': 35.6476249, 'lng': 139.6607738}
107
{'lat': 35.670506, 'lng': 139.6699829}
108
{'lat': 35.6673662, 'lng': 139.6425391}
109
{'lat': 35.6529756, 'lng': 139.6477001}
110
{'lat': 35.6510787, 'lng': 139.6385342}
111
{'lat': 35.6656829, 'lng': 139.6408056}
112
{'lat': 35.6480074, 'lng': 139.6268997}
113
{'lat': 35.6526636, 'lng': 139.6357051}
114
{'lat': 35.6214533, 'lng': 139.6313283}
115
{'lat': 35.6279922, 'lng': 139.63443}
116
{'lat': 35.6714439, 'lng': 139.6065448}
117
{'lat': 35.6215792, 'lng': 139.595056}
118
{'lat': 35.644481, 'lng': 139.6571463}
119
{'lat': 35.6677379, 'lng': 139.6329159}
120
{'lat': 35.60393699999999, 'lng': 139.6728879}
121
{'lat': 35.6353714, 'lng': 139.6640028}
122
{'lat': 35.6583133, 'lng': 139.66783}
123
{'lat': 35.6134114, 'lng': 139.6400456}
124
{'lat': 35.6358829, 'lng': 139.6654977}
125
{'lat': 35.6063906, 'lng': 139.6652386}
126
{'lat': 35.6061076, 'lng': 139.659538}
127
{'lat': 35.6321225, 'lng': 139.6580631}
128
{'lat': 35.6274713, 'lng': 139.6287722}
129
{'lat': 35.6428578, 'lng': 139.6518871}
130
{'lat': 35.64972090000001, 'lng': 139.6017153}
131
{'lat': 35.6715285, 'lng': 139.6059773}
132
{'lat': 35.6787405, 'lng': 139.6049418}
133
{'lat': 35.6628986, 'lng': 139.6688535}
134
{'lat': 35.6324066, 'lng': 139.6456675}
135
{'lat': 35.6584317, 'lng': 139.6611724}
136
{'lat': 35.6688244, 'lng': 139.6028012}
137
{'lat': 35.6018322, 'lng': 139.6438443}
138
{'lat': 35.6555938, 'lng': 139.6539833}
139
{'lat': 35.6220645, 'lng': 139.6544956}
140
{'lat': 35.6409692, 'lng': 139.6701224}
141
{'lat': 35.6206029, 'lng': 139.6247783}
142
{'lat': 35.6510523, 'lng': 139.6191114}
143
{'lat': 35.6667456, 'lng': 139.6202667}
144
{'lat': 35.6365498, 'lng': 139.6251468}
145
{'lat': 35.6051068, 'lng': 139.6738703}
146
{'lat': 35.6131559, 'lng': 139.6591394}
147
{'lat': 35.6813456, 'lng': 139.597923}
148
{'lat': 35.6057848, 'lng': 139.6366216}
149
{'lat': 35.651969, 'lng': 139.6823238}
150
{'lat': 35.6319213, 'lng': 139.6128975}
151
{'lat': 35.637846, 'lng': 139.6580532}
152
{'lat': 35.637846, 'lng': 139.6580532}
153
{'lat': 35.6529128, 'lng': 139.6146871}
154
{'lat': 35.6465315, 'lng': 139.6655622}
155
{'lat': 35.6197299, 'lng': 139.6325175}
156
{'lat': 35.6477575, 'lng': 139.6204061}
157
{'lat': 35.6457876, 'lng': 139.5924877}
158
{'lat': 35.6630987, 'lng': 139.6159944}
159
{'lat': 35.6331807, 'lng': 139.669345}
160
{'lat': 35.6230809, 'lng': 139.6521639}
161
{'lat': 35.6427293, 'lng': 139.60997}
162
{'lat': 35.6303794, 'lng': 139.644193}
163
{'lat': 35.6571478, 'lng': 139.6530806}
164
{'lat': 35.6658119, 'lng': 139.6091686}
165
{'lat': 35.6449608, 'lng': 139.6790557}
166
{'lat': 35.64211700000001, 'lng': 139.5980026}
167
{'lat': 35.6185339, 'lng': 139.6305626}
168
{'lat': 35.6383027, 'lng': 139.6792333}
169
{'lat': 35.6280886, 'lng': 139.6265212}
170
{'lat': 35.6578636, 'lng': 139.6727738}
171
{'lat': 35.6363714, 'lng': 139.6234156}
172
{'lat': 35.618232, 'lng': 139.6436749}
173
{'lat': 35.6692477, 'lng': 139.622876}
174
{'lat': 35.6659083, 'lng': 139.6375381}
175
{'lat': 35.6201556, 'lng': 139.6426188}
176
{'lat': 35.6089406, 'lng': 139.6486566}
177
{'lat': 35.6141031, 'lng': 139.6622088}
178
{'lat': 35.6188112, 'lng': 139.6223979}
179
{'lat': 35.6622895, 'lng': 139.6667535}
180
{'lat': 35.6000473, 'lng': 139.6640028}
181
{'lat': 35.6066783, 'lng': 139.658103}
182
{'lat': 35.6279044, 'lng': 139.6359043}
183
{'lat': 35.643821, 'lng': 139.6529212}
184
{'lat': 35.60104219999999, 'lng': 139.6671921}
185
{'lat': 35.6301302, 'lng': 139.6394308}
186
{'lat': 35.6614528, 'lng': 139.6666339}
187
{'lat': 35.6400107, 'lng': 139.6404669}
188
{'lat': 35.671319, 'lng': 139.6583791}
189
{'lat': 35.665659, 'lng': 139.641503}
190
{'lat': 35.6318075, 'lng': 139.6561824}
191
{'lat': 35.6475731, 'lng': 139.6306019}
192
{'lat': 35.6543438, 'lng': 139.6571363}
193
{'lat': 35.6157828, 'lng': 139.6423997}
194
{'lat': 35.6418766, 'lng': 139.6472417}
195
{'lat': 35.6164146, 'lng': 139.6509414}
196
{'lat': 35.6656208, 'lng': 139.6413635}
197
{'lat': 35.6342972, 'lng': 139.6805094}
198
{'lat': 35.6262358, 'lng': 139.6556273}

In [6]:
df.to_csv('hoikuen.csv', index=None)

In [7]:
df.head()

,区分,名称,住所,0歳定員,1歳定員,2歳定員,3歳定員,4歳定員,5歳定員,定員,受入年齢,対象年齢,開所時間,閉所時間,延長保育時間（開始）,延長保育時間（終了）,latitude,longitude
0,認可保育園,南奥沢☆,東京都世田谷区奥沢1−2−13,NaN,14.0,14.0,17.0,17.0,17.0,79,NaN,NaN,7:15:00,18:15:00,18:15:00,20:15:00,35.599453,139.680111
1,認可保育園,奥沢☆,東京都世田谷区奥沢2−3−11,10.0,10.0,11.0,17.0,17.0,18.0,83,5か月,NaN,7:15:00,18:15:00,18:15:00,20:15:00,35.605270,139.675704
2,認可保育園,中町※1,東京都世田谷区中町3−27−2,11.0,16.0,18.0,19.0,20.0,21.0,105,5か月,NaN,7:15:00,18:15:00,18:15:00,20:15:00,35.615462,139.642539
3,認可保育園,玉川,東京都世田谷区玉川4−16−6,NaN,15.0,18.0,20.0,22.0,22.0,97,NaN,NaN,7:15:00,18:15:00,18:15:00,20:15:00,35.617734,139.624131
4,認可保育園,上用賀☆,東京都世田谷区上用賀4−2−10,9.0,14.0,15.0,21.0,22.0,22.0,103,5か月,NaN,7:15:00,18:15:00,18:15:00,20:15:00,35.634891,139.630393